Repository todo-team-01/todo-max, pull requests merged in 2023-07, with the labels that each got.

#4 chore: Style-Component에서 Emotion으로 변경
  fe/.eslintrc.js
  fe/package-lock.json
  fe/package.json
  fe/src/constants/font.ts
  fe/tsconfig.json
  fe/vite.config.ts
  fe/yarn.lock
Labels: front-end, setting

#12 feat #11: 데이터 요청 초기 설정
  fe/package.json
  fe/public/mockServiceWorker.js
  fe/src/hooks/useFetch.ts
  fe/src/main.tsx
  fe/src/mocks/browser.ts
  fe/src/mocks/handlers.ts
  fe/src/utils/http.ts
  fe/yarn.lock
Labels: feat, front-end

#19 feat #15: header component 구현 및 기본 설정들 수정
  fe/src/App.css
  fe/src/App.tsx
  fe/src/assets/icon/closed.svg
  fe/src/assets/icon/edit.svg
  fe/src/assets/icon/history.svg
  fe/src/assets/icon/plus.svg
  fe/src/components/Header.tsx
  fe/src/components/base/Button.tsx
  fe/src/components/icon/ClosedIcon.tsx
  fe/src/components/icon/EditIcon.tsx
  fe/src/components/icon/HistoryIcon.tsx
  fe/src/components/icon/PlusIcon.tsx
  fe/src/constants/colors.ts
  fe/src/index.css
  fe/src/main.tsx
  fe/src/styles/index.css
  fe/src/styles/reset.css
Labels: feat, front-end

#20 feat #16 : Main component layout
  fe/src/App.tsx
  fe/src/components/Column.tsx
  fe/src/components/Main.tsx
  fe/src/hooks/useFetch.ts
Labels: feat, front-end

#23 Feat #18 : card component UI
  fe/src/components/Card.tsx
  fe/src/components/Column/Column.tsx
  fe/src/components/types.ts
  fe/src/mocks/data.ts
Labels: feat, front-end

#22 feat#9 card 추가
  be/build.gradle
  be/src/main/java/org/codesquad/todo/config/ApiException.java
  be/src/main/java/org/codesquad/todo/config/CardNotFoundException.java
  be/src/main/java/org/codesquad/todo/config/ColumnNotFoundException.java
  be/src/main/java/org/codesquad/todo/config/ErrorResponse.java
  be/src/main/java/org/codesquad/todo/config/MemberNotFoundException.java
  be/src/main/java/org/codesquad/todo/controller/CardController.java
  be/src/main/java/org/codesquad/todo/controller/dto/CardSaveRequestDto.java
  be/src/main/java/org/codesquad/todo/controller/dto/CardSaveResponseDto.java
  be/src/main/java/org/codesquad/todo/domain/card/Card.java
  be/src/main/java/org/codesquad/todo/domain/card/CardAppender.java
  be/src/main/java/org/codesquad/todo/domain/card/CardRepository.java
  be/src/main/java/org/codesquad/todo/domain/card/CardService.java
  be/src/main/java/org/codesquad/todo/domain/card/CardValidator.java
  be/src/main/java/org/codesquad/todo/domain/column/ColumnReader.java
  be/src/main/java/org/codesquad/todo/domain/column/ColumnRepository.java
  be/src/main/java/org/codesquad/todo/domain/member/MemberReader.java
  be/src/main/java/org/codesquad/todo/domain/member/MemberRepository.java
  be/src/test/java/org/codesquad/todo/TodoApplicationTests.java
  be/src/test/java/org/codesquad/todo/controller/CardControllerTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardAppenderTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardRepsitoryTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardServiceTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardValidatorTest.java
  be/src/test/java/org/codesquad/todo/util/DatabaseCleaner.java
Labels: back-end, feat, test

#14 feat #10 card 삭제 api 구현
  be/src/main/java/org/codesquad/todo/controller/CardController.java
  be/src/main/java/org/codesquad/todo/domain/card/CardRemover.java
  be/src/main/java/org/codesquad/todo/domain/card/CardRepository.java
  be/src/main/java/org/codesquad/todo/domain/card/CardService.java
Labels: back-end, feat

#32 Feature #25 : card remove edit
  fe/src/components/Card.tsx
  fe/src/components/Column/Column.tsx
  fe/src/components/Main.tsx
  fe/src/hooks/useFetch.ts
  fe/src/mocks/data.ts
  fe/src/mocks/handlers.ts
  fe/src/utils/http.ts
Labels: feat, front-end

#34 feat #24: 새로운 카드 등록 기본 기능 구현
  fe/src/components/Card.tsx
  fe/src/components/Column/Column.tsx
  fe/src/components/Main.tsx
  fe/src/components/NewCard.tsx
  fe/src/mocks/handlers.ts
  fe/src/utils/http.ts
Labels: feat, front-end

#38 feat #35 : 삭제 확인 모달창 구현
  fe/src/components/Card.tsx
  fe/src/components/base/Button.tsx
  fe/src/components/base/RemoveModal.tsx
  fe/src/constants/objectStyle.ts
Labels: feat, front-end

#39 feat #24, refactor #33: 새로운 카드 등록 버튼 기능 추가, Button Component 리팩토링
  fe/src/components/Card.tsx
  fe/src/components/Column/Badge.tsx
  fe/src/components/Column/ColumnHeader.tsx
  fe/src/components/Header.tsx
  fe/src/components/NewCard.tsx
  fe/src/components/base/Button.tsx
  fe/src/components/base/RemoveModal.tsx
Labels: feat, front-end, refactor

#42 feature #41 : history list
  fe/src/components/Header.tsx
  fe/src/components/History.tsx
  fe/src/main.tsx
  fe/src/mocks/handlers.ts
Labels: feat, front-end

#44 feat #43: Text Component 생성
  fe/src/components/Column/ColumnHeader.tsx
  fe/src/components/base/Text.tsx
Labels: feat, front-end

#45 refactor: Typography, color 디자인 시스템 전반 수정 & 컴포넌트 반영
  fe/src/components/Card.tsx
  fe/src/components/Column/Badge.tsx
  fe/src/components/Column/Column.tsx
  fe/src/components/Column/ColumnHeader.tsx
  fe/src/components/Header.tsx
  fe/src/components/History.tsx
  fe/src/components/Main.tsx
  fe/src/components/NewCard.tsx
  fe/src/components/base/Button.tsx
  fe/src/components/base/Text.tsx
  fe/src/constants/colors.ts
  fe/src/constants/font.ts
Labels: front-end, refactor

#47 feature #37: column 추가,삭제, 수정 API 구현
  be/build.gradle
  be/src/main/java/org/codesquad/todo/config/CardNotFoundException.java
  be/src/main/java/org/codesquad/todo/config/ColumnNotFoundException.java
  be/src/main/java/org/codesquad/todo/config/MemberNotFoundException.java
  be/src/main/java/org/codesquad/todo/controller/ColumnController.java
  be/src/main/java/org/codesquad/todo/controller/dto/ColumnCardResponseDTO.java
  be/src/main/java/org/codesquad/todo/controller/dto/ColumnSaveRequestDTO.java
  be/src/main/java/org/codesquad/todo/controller/dto/ColumnSaveResponseDTO.java
  be/src/main/java/org/codesquad/todo/controller/dto/ColumnUpdateRequestDTO.java
  be/src/main/java/org/codesquad/todo/domain/card/CardRepository.java
  be/src/main/java/org/codesquad/todo/domain/card/CardService.java
  be/src/main/java/org/codesquad/todo/domain/column/ColumnAppender.java
  be/src/main/java/org/codesquad/todo/domain/column/ColumnManager.java
  be/src/main/java/org/codesquad/todo/domain/column/ColumnReader.java
  be/src/main/java/org/codesquad/todo/domain/column/ColumnRemover.java
  be/src/main/java/org/codesquad/todo/domain/column/ColumnRepository.java
  be/src/main/java/org/codesquad/todo/domain/column/ColumnService.java
  be/src/main/java/org/codesquad/todo/domain/column/ColumnWithCard.java
  be/src/test/java/org/codesquad/todo/controller/CardAcceptanceTest.java
  be/src/test/java/org/codesquad/todo/controller/CardControllerTest.java
  be/src/test/java/org/codesquad/todo/controller/ColumnAcceptanceTest.java
  be/src/test/java/org/codesquad/todo/controller/ColumnControllerTest.java
  be/src/test/java/org/codesquad/todo/controller/util/AcceptanceTest.java
  be/src/test/java/org/codesquad/todo/controller/util/CardSteps.java
  be/src/test/java/org/codesquad/todo/controller/util/ColumnSteps.java
  be/src/test/java/org/codesquad/todo/domain/card/CardReaderTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardRepositoryTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnAppenderTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnManagerTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnReaderTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnRemoverTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnRepositoryTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnServiceTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnWithCardTest.java
  be/src/test/java/org/codesquad/todo/util/DatabaseCleaner.java
Labels: back-end, feat, test

#46 refactor #43 : Card 컴포넌트 css 작업 및 구조 리팩토링
  fe/src/components/Card.tsx
  fe/src/components/Card/Card.tsx
  fe/src/components/Card/CardEditor.tsx
  fe/src/components/Card/CardViewer.tsx
  fe/src/components/Card/NewCard.tsx
  fe/src/components/Column/Column.tsx
  fe/src/components/Header.tsx
  fe/src/components/NewCard.tsx
  fe/src/mocks/handlers.ts
Labels: design, front-end, refactor

#48 design #43 : column 컴포넌트 css 적용
  fe/src/App.tsx
  fe/src/components/Column/Column.tsx
  fe/src/components/Main.tsx
Labels: design, front-end

#51 refactor: #43 ActionHistoryList 리팩토링 & CSS 작업
  fe/index.html
  fe/public/assets/profile.jpg
  fe/src/App.tsx
  fe/src/components/ActionHistoryList/ActionHistoryList.tsx
  fe/src/components/ActionHistoryList/ClearArea.tsx
  fe/src/components/ActionHistoryList/ListArea/ActionText.tsx
  fe/src/components/ActionHistoryList/ListArea/ListArea.tsx
  fe/src/components/ActionHistoryList/ListArea/TimeStamp.tsx
  fe/src/components/ActionHistoryList/ListArea/index.tsx
  fe/src/components/ActionHistoryList/TitleArea.tsx
  fe/src/components/ActionHistoryList/index.tsx
  fe/src/components/Header.tsx
  fe/src/components/History.tsx
  fe/src/components/Main.tsx
  fe/src/components/base/RemoveModal.tsx
  fe/src/hooks/useFetch.ts
  fe/src/mocks/data.ts
  fe/src/mocks/handlers.ts
Labels: feat, front-end, refactor

#53 fix #52: 카드 위치를 position으로 바꾼 후 카드 등록 API 수정
  be/build.gradle
  be/src/main/java/org/codesquad/todo/config/MemberNotFoundException.java
  be/src/main/java/org/codesquad/todo/controller/CardController.java
  be/src/main/java/org/codesquad/todo/controller/dto/CardSaveRequestDto.java
  be/src/main/java/org/codesquad/todo/controller/dto/CardSaveResponseDto.java
  be/src/main/java/org/codesquad/todo/controller/dto/ColumnCardResponseDTO.java
  be/src/main/java/org/codesquad/todo/domain/card/Card.java
  be/src/main/java/org/codesquad/todo/domain/card/CardAppender.java
  be/src/main/java/org/codesquad/todo/domain/card/CardManager.java
  be/src/main/java/org/codesquad/todo/domain/card/CardReader.java
  be/src/main/java/org/codesquad/todo/domain/card/CardRepository.java
  be/src/main/java/org/codesquad/todo/domain/card/CardService.java
  be/src/main/java/org/codesquad/todo/domain/card/CardValidator.java
  be/src/main/java/org/codesquad/todo/domain/column/ColumnWithCard.java
  be/src/main/java/org/codesquad/todo/domain/member/MemberReader.java
  be/src/main/java/org/codesquad/todo/domain/member/MemberRepository.java
  be/src/main/java/org/codesquad/todo/domain/member/MemberValidator.java
  be/src/main/resources/schema.sql
  be/src/test/java/org/codesquad/todo/controller/CardAcceptanceTest.java
  be/src/test/java/org/codesquad/todo/controller/util/AcceptanceTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardAppenderTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardManagerTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardReaderTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardRepositoryTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardServiceTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardValidatorTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnServiceTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnWithCardTest.java
  be/src/test/resources/schema.sql
Labels: back-end, fix, test

#57 feat #54: AOP을 활용한 History 조회 및 등록 API 구현
  be/src/main/java/org/codesquad/todo/config/HistoryAspect.java
  be/src/main/java/org/codesquad/todo/controller/HistoryController.java
  be/src/main/java/org/codesquad/todo/controller/dto/HistoryResponseDto.java
  be/src/main/java/org/codesquad/todo/domain/history/History.java
  be/src/main/java/org/codesquad/todo/domain/history/HistoryAppender.java
  be/src/main/java/org/codesquad/todo/domain/history/HistoryReader.java
  be/src/main/java/org/codesquad/todo/domain/history/HistoryRemover.java
  be/src/main/java/org/codesquad/todo/domain/history/HistoryRepository.java
  be/src/main/java/org/codesquad/todo/domain/history/HistoryService.java
  be/src/main/resources/schema.sql
  be/src/test/java/org/codesquad/todo/controller/CardAcceptanceTest.java
  be/src/test/java/org/codesquad/todo/controller/ColumnAcceptanceTest.java
  be/src/test/java/org/codesquad/todo/controller/HistoryAcceptanceTest.java
  be/src/test/java/org/codesquad/todo/controller/util/HistorySteps.java
  be/src/test/java/org/codesquad/todo/domain/card/CardReaderTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardRepositoryTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnAppenderTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnReaderTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnRepositoryTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnServiceTest.java
  be/src/test/java/org/codesquad/todo/domain/history/HistoryAppenderTest.java
  be/src/test/java/org/codesquad/todo/domain/history/HistoryReaderTest.java
  be/src/test/java/org/codesquad/todo/domain/history/HistoryRemoverTest.java
  be/src/test/java/org/codesquad/todo/domain/history/HistoryRepositoryTest.java
  be/src/test/java/org/codesquad/todo/domain/history/HistoryServiceTest.java
  be/src/test/resources/schema.sql
Labels: back-end, feat, test

#61 Feature/#55 card move
  be/src/main/java/org/codesquad/todo/controller/CardController.java
  be/src/main/java/org/codesquad/todo/controller/dto/CardMoveRequestDto.java
  be/src/main/java/org/codesquad/todo/domain/card/CardManager.java
  be/src/main/java/org/codesquad/todo/domain/card/CardRepository.java
  be/src/main/java/org/codesquad/todo/domain/card/CardService.java
  be/src/main/java/org/codesquad/todo/domain/card/CardValidator.java
  be/src/test/java/org/codesquad/todo/controller/CardAcceptanceTest.java
  be/src/test/java/org/codesquad/todo/controller/util/CardSteps.java
  be/src/test/java/org/codesquad/todo/domain/card/CardManagerTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardRepositoryTest.java
  be/src/test/java/org/codesquad/todo/util/DatabaseCleaner.java
Labels: back-end, feat, test

#56 refactor #43: 카드 등록 API 변경사항 반영 및 http 리팩토링
  fe/src/components/Card/CardEditor.tsx
  fe/src/components/Card/NewCard.tsx
  fe/src/components/Column/Column.tsx
  fe/src/mocks/handlers.ts
  fe/src/utils/http.ts
Labels: front-end, refactor

#63 feat #40 : card move
  .github/ISSUE_TEMPLATE/backend.md
  .github/ISSUE_TEMPLATE/frontend.md
  .github/PULL_REQUEST_TEMPLATE.md
  fe/package.json
  fe/src/components/Card/Card.tsx
  fe/src/components/Card/CloneCard.tsx
  fe/src/components/Column/Column.tsx
  fe/src/components/Main.tsx
  fe/src/hooks/useFetch.ts
  fe/src/mocks/data.ts
  fe/src/mocks/handlers.ts
  fe/src/utils/http.ts
  fe/yarn.lock
Labels: feat, front-end, refactor, setting

#65 feat #59: 모든 API RestDocs 작성
  be/build.gradle
  be/src/main/java/org/codesquad/todo/config/ErrorResponse.java
  be/src/main/java/org/codesquad/todo/controller/CardController.java
  be/src/main/java/org/codesquad/todo/controller/ColumnController.java
  be/src/main/java/org/codesquad/todo/controller/HistoryController.java
  be/src/main/java/org/codesquad/todo/controller/dto/CardModifyRequestDto.java
  be/src/main/java/org/codesquad/todo/controller/dto/CardResponseDTO.java
  be/src/main/java/org/codesquad/todo/controller/dto/ColumnSaveResponseDTO.java
  be/src/main/java/org/codesquad/todo/controller/dto/HistoryResponseDto.java
  be/src/main/java/org/codesquad/todo/domain/card/CardService.java
  be/src/main/java/org/codesquad/todo/domain/column/Column.java
  be/src/main/java/org/codesquad/todo/domain/column/ColumnAppender.java
  be/src/main/java/org/codesquad/todo/domain/column/ColumnRepository.java
  be/src/main/java/org/codesquad/todo/domain/column/ColumnService.java
  be/src/main/java/org/codesquad/todo/domain/history/HistoryRepository.java
  be/src/test/java/org/codesquad/todo/controller/CardAcceptanceTest.java
  be/src/test/java/org/codesquad/todo/controller/CardControllerTest.java
  be/src/test/java/org/codesquad/todo/controller/ColumnAcceptanceTest.java
  be/src/test/java/org/codesquad/todo/controller/ColumnControllerTest.java
  be/src/test/java/org/codesquad/todo/controller/HistoryAcceptanceTest.java
  be/src/test/java/org/codesquad/todo/controller/HistoryControllerTest.java
  be/src/test/java/org/codesquad/todo/controller/util/CardSteps.java
  be/src/test/java/org/codesquad/todo/controller/util/ColumnSteps.java
  be/src/test/java/org/codesquad/todo/controller/util/HistorySteps.java
  be/src/test/java/org/codesquad/todo/domain/card/CardAppenderTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardManagerTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardReaderTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardRepositoryTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardServiceTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardValidatorTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnAppenderTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnManagerTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnReaderTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnRemoverTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnRepositoryTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnServiceTest.java
  be/src/test/java/org/codesquad/todo/domain/column/ColumnValidatorTest.java
  be/src/test/java/org/codesquad/todo/domain/history/HistoryAppenderTest.java
  be/src/test/java/org/codesquad/todo/domain/history/HistoryReaderTest.java
  be/src/test/java/org/codesquad/todo/domain/history/HistoryRemoverTest.java
  be/src/test/java/org/codesquad/todo/domain/history/HistoryRepositoryTest.java
  be/src/test/java/org/codesquad/todo/domain/history/HistoryServiceTest.java
  be/src/test/java/org/codesquad/todo/util/AcceptanceTest.java
  be/src/test/java/org/codesquad/todo/util/ControllerTest.java
  be/src/test/java/org/codesquad/todo/util/RepositoryTest.java
  be/src/test/java/org/codesquad/todo/util/ServiceTest.java
Labels: back-end, feat, test

#64 Feat/#58 column add delete edit
  fe/src/components/ActionHistoryList/ActionHistoryList.tsx
  fe/src/components/ActionHistoryList/ListArea/ListArea.tsx
  fe/src/components/ActionHistoryList/ListArea/TimeStamp.tsx
  fe/src/components/Column/Column.tsx
  fe/src/components/Column/ColumnButtons.tsx
  fe/src/components/Column/ColumnHeader.tsx
  fe/src/components/Column/NameEditor.tsx
  fe/src/components/FAB.tsx
  fe/src/components/Main.tsx
  fe/src/components/base/Button.tsx
  fe/src/hooks/useOutsideClick.ts
  fe/src/mocks/handlers.ts
Labels: feat, front-end

#68 feat #66: AOP를 활용한 History 이동 API 구현
  be/src/main/java/org/codesquad/todo/config/HistoryAspect.java
  be/src/test/java/org/codesquad/todo/controller/CardAcceptanceTest.java
Labels: back-end, feat, test

#70 feat #69: CORS 구현
  be/src/main/java/org/codesquad/todo/config/WebConfig.java
Labels: back-end, feat

#71 Fix #67 카드 이동 검증
  be/src/main/java/org/codesquad/todo/config/InvalidCardException.java
  be/src/main/java/org/codesquad/todo/domain/card/CardManager.java
  be/src/main/java/org/codesquad/todo/domain/card/CardReader.java
  be/src/main/java/org/codesquad/todo/domain/card/CardRepository.java
  be/src/main/java/org/codesquad/todo/domain/card/CardValidator.java
  be/src/test/java/org/codesquad/todo/domain/card/CardManagerTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardReaderTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardRepositoryTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardValidatorTest.java
Labels: back-end, fix

#73 fix #72: 커넥션 반환 안 되어 테스트 실패하는 버그 수정
  be/src/docs/asciidoc/card.adoc
  be/src/docs/asciidoc/column.adoc
  be/src/docs/asciidoc/history.adoc
  be/src/main/resources/schema.sql
  be/src/main/resources/static/docs/card.html
  be/src/main/resources/static/docs/column.html
  be/src/main/resources/static/docs/history.html
  be/src/test/java/org/codesquad/todo/util/DatabaseCleaner.java
Labels: back-end, feat, fix

#76 fix #75: patch cors 설정 추가
  be/src/main/java/org/codesquad/todo/config/WebConfig.java
Labels: back-end, fix

#74 refactor #40 : card move 성능 개선, 오류 수정
  fe/src/components/Card/Card.tsx
  fe/src/components/Card/CardEditor.tsx
  fe/src/components/Card/CardViewer.tsx
  fe/src/components/Card/CloneCard.tsx
  fe/src/components/Column/Column.tsx
  fe/src/components/Main.tsx
  fe/src/hooks/useFetch.ts
  fe/src/mocks/data.ts
  fe/src/mocks/handlers.ts
Labels: fix, front-end, refactor

#80 fix #79: 빈 컬럼으로 카드 이동이 불가하던 오류 수정
  be/src/main/java/org/codesquad/todo/domain/card/CardManager.java
  be/src/main/java/org/codesquad/todo/domain/card/CardRepository.java
  be/src/main/java/org/codesquad/todo/domain/card/CardValidator.java
  be/src/test/java/org/codesquad/todo/domain/card/CardManagerTest.java
  be/src/test/java/org/codesquad/todo/domain/card/CardValidatorTest.java
Labels: back-end, fix

#82 fix #81: 인수 테스트 TEST DB 설정 추가
  be/src/test/java/org/codesquad/todo/util/AcceptanceTest.java
Labels: back-end, fix, test

#86 fix #84 : 버그 수정 및 리팩토링
  fe/src/components/ActionHistoryList/ActionHistoryList.tsx
  fe/src/components/Card/Card.tsx
  fe/src/components/Main.tsx
Labels: fix, front-end

#87 Fix/#85 be card move bug
  be/src/main/java/org/codesquad/todo/config/CardInvalidSequentialException.java
  be/src/main/java/org/codesquad/todo/domain/card/CardRepository.java
  be/src/main/java/org/codesquad/todo/domain/card/CardValidator.java
Labels: back-end, fix

#88 refactor: useFetch hook 개선 및 반영 & 카드 이동 일부 수정
  fe/index.html
  fe/src/components/Card/CardEditor.tsx
  fe/src/components/Column/NameEditor.tsx
  fe/src/components/FAB.tsx
  fe/src/components/Main.tsx
  fe/src/hooks/useFetch.ts
  fe/src/utils/http.ts
Labels: front-end, refactor

#91 Refactor/#89 card
  fe/src/components/Card/Card.tsx
  fe/src/components/Card/CardEditor.tsx
  fe/src/components/Card/CardViewer.tsx
  fe/src/components/Column/Column.tsx
  fe/src/components/Header.tsx
  fe/src/components/Main.tsx
  fe/src/utils/http.ts
Labels: feat, front-end, refactor
